#!/usr/bin/env bash

declare -x INVOICENINJA_BASE_DIR
: "${INVOICENINJA_BASE_DIR:="/var/lib/invoiceninja"}"

declare -x INVOICENINJA_APP_DIR
: "${INVOICENINJA_APP_DIR:="${INVOICENINJA_BASE_DIR}/app"}"

declare -x INVOICENINJA_LOGS_DIR
: "${INVOICENINJA_LOGS_DIR:="${INVOICENINJA_BASE_DIR}/logs"}"

declare -x INVOICENINJA_SKIP_CHOWN
: "${INVOICENINJA_SKIP_CHOWN:="false"}"
