#!/bin/bash

declare -x INVOICENINJA_CACHE_DRIVER
[[ -z "${INVOICENINJA_CACHE_DRIVER}" ]] && INVOICENINJA_CACHE_DRIVER="file"

declare -x INVOICENINJA_CACHE_DATABASE
[[ -z "${INVOICENINJA_CACHE_DATABASE}" ]] && INVOICENINJA_CACHE_DATABASE="${INVOICENINJA_DB_TYPE}"

declare -x INVOICENINJA_CACHE_MEMCACHED_HOST
[[ -z "${INVOICENINJA_CACHE_MEMCACHED_HOST}" ]] && INVOICENINJA_CACHE_MEMCACHED_HOST="memcached"

declare -x INVOICENINJA_CACHE_MEMCACHED_PORT
[[ -z "${INVOICENINJA_CACHE_MEMCACHED_PORT}" ]] && INVOICENINJA_CACHE_MEMCACHED_PORT="11211"
