<?php

use App\Libraries\Utils;

return [
  'name' => env('INVOICENINJA_APP_NAME', 'Invoice Ninja'),
  'debug' => env('INVOICENINJA_APP_DEBUG', ''),
  'env' => env('INVOICENINJA_APP_ENV', 'production'),
  'url' => env('INVOICENINJA_APP_URL', ''),
  'timezone' => env('INVOICENINJA_APP_TIMEZONE', 'UTC'),
  'locale' => env('INVOICENINJA_APP_LOCALE', 'en'),
  'fallback_locale' => env('INVOICENINJA_APP_FALLBACK_LOCALE', 'en'),
  'key' => env('INVOICENINJA_APP_KEY', ''),
  'cipher' => env('INVOICENINJA_APP_CIPHER', 'AES-256-CBC'),
  'log' => env('INVOICENINJA_APP_LOG', 'single'),

  'providers' => [
    'Illuminate\Auth\AuthServiceProvider',
    'Collective\Html\HtmlServiceProvider',
    'Illuminate\Bus\BusServiceProvider',
    'Illuminate\Cache\CacheServiceProvider',
    'Illuminate\Foundation\Providers\ConsoleSupportServiceProvider',
    'Illuminate\Cookie\CookieServiceProvider',
    'Illuminate\Database\DatabaseServiceProvider',
    'Illuminate\Encryption\EncryptionServiceProvider',
    'Illuminate\Filesystem\FilesystemServiceProvider',
    'Illuminate\Foundation\Providers\FoundationServiceProvider',
    'Illuminate\Hashing\HashServiceProvider',
    'Illuminate\Mail\MailServiceProvider',
    'Illuminate\Pagination\PaginationServiceProvider',
    'Illuminate\Pipeline\PipelineServiceProvider',
    'Illuminate\Queue\QueueServiceProvider',
    'Illuminate\Redis\RedisServiceProvider',
    'Illuminate\Auth\Passwords\PasswordResetServiceProvider',
    'Illuminate\Session\SessionServiceProvider',
    'Illuminate\Translation\TranslationServiceProvider',
    'Illuminate\Validation\ValidationServiceProvider',
    'Illuminate\View\ViewServiceProvider',
    'Illuminate\Broadcasting\BroadcastServiceProvider',
    'Illuminate\Notifications\NotificationServiceProvider',
    'Bootstrapper\BootstrapperL5ServiceProvider',
    'Former\FormerServiceProvider',
    'Barryvdh\Debugbar\ServiceProvider',
    'Intervention\Image\ImageServiceProvider',
    'Webpatser\Countries\CountriesServiceProvider',
    'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider',
    'Laravel\Socialite\SocialiteServiceProvider',
    'Jlapp\Swaggervel\SwaggervelServiceProvider',
    'Maatwebsite\Excel\ExcelServiceProvider',
    Websight\GcsProvider\CloudStorageServiceProvider::class,
    'Jaybizzle\LaravelCrawlerDetect\LaravelCrawlerDetectServiceProvider',
    Codedge\Updater\UpdaterServiceProvider::class,
    Nwidart\Modules\LaravelModulesServiceProvider::class,
    Barryvdh\Cors\ServiceProvider::class,
    PragmaRX\Google2FALaravel\ServiceProvider::class,
    'Chumper\Datatable\DatatableServiceProvider',
    Laravel\Tinker\TinkerServiceProvider::class,
    'App\Providers\AuthServiceProvider',
    'App\Providers\AppServiceProvider',
    'App\Providers\ComposerServiceProvider',
    'App\Providers\ConfigServiceProvider',
    'App\Providers\EventServiceProvider',
    'App\Providers\RouteServiceProvider',
    'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider',
    'Davibennun\LaravelPushNotification\LaravelPushNotificationServiceProvider',
  ],

  'aliases' => [
    'App' => 'Illuminate\Support\Facades\App',
    'Artisan' => 'Illuminate\Support\Facades\Artisan',
    'Auth' => 'Illuminate\Support\Facades\Auth',
    'Blade' => 'Illuminate\Support\Facades\Blade',
    'Cache' => 'Illuminate\Support\Facades\Cache',
    'ClassLoader' => 'Illuminate\Support\ClassLoader',
    'Config' => 'Illuminate\Support\Facades\Config',
    'Controller' => 'Illuminate\Routing\Controller',
    'Cookie' => 'Illuminate\Support\Facades\Cookie',
    'Crypt' => 'Illuminate\Support\Facades\Crypt',
    'DB' => 'Illuminate\Support\Facades\DB',
    'Eloquent' => 'Illuminate\Database\Eloquent\Model',
    'Event' => 'Illuminate\Support\Facades\Event',
    'File' => 'Illuminate\Support\Facades\File',
    'Gate' => 'Illuminate\Support\Facades\Gate',
    'Hash' => 'Illuminate\Support\Facades\Hash',
    'Input' => 'Illuminate\Support\Facades\Input',
    'Lang' => 'Illuminate\Support\Facades\Lang',
    'Log' => 'Illuminate\Support\Facades\Log',
    'Mail' => 'Illuminate\Support\Facades\Mail',
    'Password' => 'Illuminate\Support\Facades\Password',
    'Queue' => 'Illuminate\Support\Facades\Queue',
    'Redirect' => 'Illuminate\Support\Facades\Redirect',
    'Redis' => 'Illuminate\Support\Facades\Redis',
    'Request' => 'Illuminate\Support\Facades\Request',
    'Response' => 'Illuminate\Support\Facades\Response',
    'Route' => 'Illuminate\Support\Facades\Route',
    'Schema' => 'Illuminate\Support\Facades\Schema',
    'Seeder' => 'Illuminate\Database\Seeder',
    'Session' => 'Illuminate\Support\Facades\Session',
    'Storage' => 'Illuminate\Support\Facades\Storage',
    'Str' => 'Illuminate\Support\Str',
    'URL' => 'Illuminate\Support\Facades\URL',
    'Validator' => 'Illuminate\Support\Facades\Validator',
    'View' => 'Illuminate\Support\Facades\View',
    'Form' => 'Collective\Html\FormFacade',
    'HTML' => 'Collective\Html\HtmlFacade',
    'SSH' => 'Illuminate\Support\Facades\SSH',
    'Alert' => 'Bootstrapper\Facades\Alert',
    'Badge' => 'Bootstrapper\Facades\Badge',
    'Breadcrumb' => 'Bootstrapper\Facades\Breadcrumb',
    'Button' => 'Bootstrapper\Facades\Button',
    'ButtonGroup' => 'Bootstrapper\Facades\ButtonGroup',
    'ButtonToolbar' => 'Bootstrapper\Facades\ButtonToolbar',
    'Carousel' => 'Bootstrapper\Facades\Carousel',
    'DropdownButton' => 'Bootstrapper\Facades\DropdownButton',
    'Helpers' => 'Bootstrapper\Facades\Helpers',
    'Icon' => 'Bootstrapper\Facades\Icon',
    'Label' => 'Bootstrapper\Facades\Label',
    'MediaObject' => 'Bootstrapper\Facades\MediaObject',
    'Navbar' => 'Bootstrapper\Facades\Navbar',
    'Navigation' => 'Bootstrapper\Facades\Navigation',
    'Paginator' => 'Bootstrapper\Facades\Paginator',
    'Progress' => 'Bootstrapper\Facades\Progress',
    'Tabbable' => 'Bootstrapper\Facades\Tabbable',
    'Table' => 'Bootstrapper\Facades\Table',
    'Thumbnail' => 'Bootstrapper\Facades\Thumbnail',
    'Typeahead' => 'Bootstrapper\Facades\Typeahead',
    'Typography' => 'Bootstrapper\Facades\Typography',
    'Former' => 'Former\Facades\Former',
    'Omnipay' => 'Omnipay\Omnipay',
    'CreditCard' => 'Omnipay\Common\CreditCard',
    'Image' => 'Intervention\Image\Facades\Image',
    'Countries' => 'Webpatser\Countries\CountriesFacade',
    'Carbon' => 'Carbon\Carbon',
    'Rocketeer' => 'Rocketeer\Facades\Rocketeer',
    'Socialite' => 'Laravel\Socialite\Facades\Socialite',
    'Excel' => 'Maatwebsite\Excel\Facades\Excel',
    'PushNotification' => 'Davibennun\LaravelPushNotification\Facades\PushNotification',
    'Crawler' => 'Jaybizzle\LaravelCrawlerDetect\Facades\LaravelCrawlerDetect',
    'Datatable' => 'Chumper\Datatable\Facades\DatatableFacade',
    'Updater' => Codedge\Updater\UpdaterFacade::class,
    'Module' => Nwidart\Modules\Facades\Module::class,
    'Utils' => App\Libraries\Utils::class,
    'DateUtils' => App\Libraries\DateUtils::class,
    'HTMLUtils' => App\Libraries\HTMLUtils::class,
    'CurlUtils' => App\Libraries\CurlUtils::class,
    'Domain' => App\Constants\Domain::class,
    'Google2FA' => PragmaRX\Google2FALaravel\Facade::class,
  ],
];
