#!/usr/bin/env bash

declare -x INVOICENINJA_GOOGLE_PLAY_PACKAGE_NAME
[[ -z "${INVOICENINJA_GOOGLE_PLAY_PACKAGE_NAME}" ]] && INVOICENINJA_GOOGLE_PLAY_PACKAGE_NAME=""

declare -x INVOICENINJA_GOOGLE_APPLICATION_CREDENTIALS
[[ -z "${INVOICENINJA_GOOGLE_APPLICATION_CREDENTIALS}" ]] && INVOICENINJA_GOOGLE_APPLICATION_CREDENTIALS=""

declare -x INVOICENINJA_APPSTORE_PASSWORD
[[ -z "${INVOICENINJA_APPSTORE_PASSWORD}" ]] && INVOICENINJA_APPSTORE_PASSWORD=""

declare -x INVOICENINJA_APPSTORE_PRIVATE_KEY_ID
[[ -z "${INVOICENINJA_APPSTORE_PRIVATE_KEY_ID}" ]] && INVOICENINJA_APPSTORE_PRIVATE_KEY_ID=""

declare -x INVOICENINJA_APPSTORE_PRIVATE_KEY
[[ -z "${INVOICENINJA_APPSTORE_PRIVATE_KEY}" ]] && INVOICENINJA_APPSTORE_PRIVATE_KEY=""

declare -x INVOICENINJA_APPSTORE_ISSUER_ID
[[ -z "${INVOICENINJA_APPSTORE_ISSUER_ID}" ]] && INVOICENINJA_APPSTORE_ISSUER_ID=""

declare -x INVOICENINJA_APPSTORE_BUNDLE_ID
[[ -z "${INVOICENINJA_APPSTORE_BUNDLE_ID}" ]] && INVOICENINJA_APPSTORE_BUNDLE_ID=""

true
