#!/usr/bin/env bash

declare -x INVOICENINJA_LOG_CHANNEL
: "${INVOICENINJA_LOG_CHANNEL:="stack"}"

declare -x INVOICENINJA_LOG_DEPRECATIONS_CHANNEL
: "${INVOICENINJA_LOG_DEPRECATIONS_CHANNEL:="null"}"

declare -x INVOICENINJA_LOG_LEVEL
: "${INVOICENINJA_LOG_LEVEL:="debug"}"

declare -x INVOICENINJA_PAPERTRAIL_URL
: "${INVOICENINJA_PAPERTRAIL_URL:=""}"

declare -x INVOICENINJA_PAPERTRAIL_PORT
: "${INVOICENINJA_PAPERTRAIL_PORT:=""}"

declare -x INVOICENINJA_LOG_STDERR_FORMATTER
: "${INVOICENINJA_LOG_STDERR_FORMATTER:=""}"

declare -x INVOICENINJA_GRAYLOG_SERVER
: "${INVOICENINJA_GRAYLOG_SERVER:=""}"
