#!/usr/bin/env bash

declare -x INVOICENINJA_MAIL_MAILER
: "${INVOICENINJA_MAIL_MAILER:="smtp"}"

declare -x INVOICENINJA_MAIL_HOST
: "${INVOICENINJA_MAIL_HOST:=""}"

declare -x INVOICENINJA_MAIL_PORT
: "${INVOICENINJA_MAIL_PORT:="587"}"

declare -x INVOICENINJA_MAIL_ENCRYPTION
: "${INVOICENINJA_MAIL_ENCRYPTION:="tls"}"

declare -x INVOICENINJA_MAIL_USERNAME
: "${INVOICENINJA_MAIL_USERNAME:=""}"

declare -x INVOICENINJA_MAIL_PASSWORD
: "${INVOICENINJA_MAIL_PASSWORD:=""}"

declare -x INVOICENINJA_MAIL_EHLO_DOMAIN
: "${INVOICENINJA_MAIL_EHLO_DOMAIN:=""}"

declare -x INVOICENINJA_MAIL_VERIFY_PEER
: "${INVOICENINJA_MAIL_VERIFY_PEER:=""}"

declare -x INVOICENINJA_MAIL_SENDMAIL_PATH
: "${INVOICENINJA_MAIL_SENDMAIL_PATH:=""}"

declare -x INVOICENINJA_MAIL_LOG_CHANNEL
: "${INVOICENINJA_MAIL_LOG_CHANNEL:=""}"

declare -x INVOICENINJA_MAIL_FROM_ADDRESS
: "${INVOICENINJA_MAIL_FROM_ADDRESS:="invoiceninja@localhost"}"

declare -x INVOICENINJA_MAIL_FROM_NAME
: "${INVOICENINJA_MAIL_FROM_NAME:="Invoiceninja"}"
