#!/bin/bash

for DIR in app logs templates
do
  if [ ! -d /storage/${DIR} ]
  then
    mkdir -p \
      /storage/${DIR}
  fi

  rm -rf \
    /srv/www/storage/${DIR}

  ln -sf \
    /storage/${DIR} \
    /srv/www/storage/${DIR}
done

if [ ! -f /storage/templates/bold.js ]
then
  wget \
    -qO /storage/templates/bold.js \
    https://raw.githubusercontent.com/invoiceninja/invoiceninja/v2.4.9.1/storage/templates/bold.js
fi

if [ ! -f /storage/templates/clean.js ]
then
  wget \
    -qO /storage/templates/clean.js \
    https://raw.githubusercontent.com/invoiceninja/invoiceninja/v2.4.9.1/storage/templates/clean.js
fi

if [ ! -f /storage/templates/modern.js ]
then
  wget \
    -qO /storage/templates/modern.js \
    https://raw.githubusercontent.com/invoiceninja/invoiceninja/v2.4.9.1/storage/templates/modern.js
fi

if [ ! -f /storage/templates/plain.js ]
then
  wget \
    -qO /storage/templates/plain.js \
    https://raw.githubusercontent.com/invoiceninja/invoiceninja/v2.4.9.1/storage/templates/plain.js
fi
