FROM ghcr.io/dockhippie/php-apache:8.4-amd64@sha256:8f1a87b2d4f1f705160af532ff5578c716b2d34580abe1411b5f6f9be8189d09

VOLUME ["/var/lib/invoiceninja"]
EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  apk add php${PHP_PACKAGE_VERSION}-pecl-apcu sqlite git && \
  rm -rf /var/cache/apk/*

ENV PHP_COMPOSER_INSTALL=false

# renovate: datasource=github-releases depName=invoiceninja/invoiceninja
ENV INVOICENINJA_VERSION=5.9.9

# renovate: datasource=github-releases depName=aptible/supercronic
ENV SUPERCRONIC_VERSION=0.2.34

RUN curl -sSLo - https://github.com/invoiceninja/invoiceninja/releases/download/v${INVOICENINJA_VERSION}/invoiceninja.tar | tar -xzf - -C /srv/www && \
  cd /srv/www && \
  rm -f /srv/www/.env* && \
  chown -R apache:apache /srv/www && \
  curl -sSLo /usr/bin/supercronic https://github.com/aptible/supercronic/releases/download/v${SUPERCRONIC_VERSION}/supercronic-linux-amd64 && \
  chmod +x /usr/bin/supercronic

COPY ./overlay /
