#!/usr/bin/env bash

declare -x INVOICENINJA_APP_LOGO
: "${INVOICENINJA_APP_LOGO:=""}"

declare -x INVOICENINJA_APP_DOMAIN
: "${INVOICENINJA_APP_DOMAIN:=""}"

declare -x INVOICENINJA_ADMIN_TOKEN
: "${INVOICENINJA_ADMIN_TOKEN:=""}"

declare -x INVOICENINJA_PROD
: "${INVOICENINJA_PROD:=""}"

declare -x INVOICENINJA_LICENSE
: "${INVOICENINJA_LICENSE:=""}"

declare -x INVOICENINJA_CLIENT_PORTAL
: "${INVOICENINJA_CLIENT_PORTAL:=""}"

declare -x INVOICENINJA_REQUIRE_HTTPS
: "${INVOICENINJA_REQUIRE_HTTPS:=""}"

declare -x INVOICENINJA_API_SECRET
: "${INVOICENINJA_API_SECRET:=""}"

declare -x INVOICENINJA_GOOGLE_MAPS_API_KEY
: "${INVOICENINJA_GOOGLE_MAPS_API_KEY:=""}"

declare -x INVOICENINJA_GOOGLE_ANALYTICS_URL
: "${INVOICENINJA_GOOGLE_ANALYTICS_URL:=""}"

declare -x INVOICENINJA_ERROR_EMAIL
: "${INVOICENINJA_ERROR_EMAIL:=""}"

declare -x INVOICENINJA_HASH_SALT
: "${INVOICENINJA_HASH_SALT:=""}"

declare -x INVOICENINJA_OPENEXCHANGE_APP_ID
: "${INVOICENINJA_OPENEXCHANGE_APP_ID:=""}"

declare -x INVOICENINJA_PHANTOMJS_KEY
: "${INVOICENINJA_PHANTOMJS_KEY:=""}"

declare -x INVOICENINJA_PHANTOMJS_SECRET
: "${INVOICENINJA_PHANTOMJS_SECRET:=""}"

declare -x INVOICENINJA_PHANTOMJS_PDF_GENERATION
: "${INVOICENINJA_PHANTOMJS_PDF_GENERATION:=""}"

declare -x INVOICENINJA_PDF_GENERATOR
: "${INVOICENINJA_PDF_GENERATOR:=""}"

declare -x INVOICENINJA_TRUSTED_PROXIES
: "${INVOICENINJA_TRUSTED_PROXIES:=""}"

declare -x INVOICENINJA_LOCAL_DOWNLOAD
: "${INVOICENINJA_LOCAL_DOWNLOAD:=""}"

declare -x INVOICENINJA_SENTRY_LARAVEL_DSN
: "${INVOICENINJA_SENTRY_LARAVEL_DSN:=""}"

declare -x INVOICENINJA_PRECONFIGURED_INSTALL
: "${INVOICENINJA_PRECONFIGURED_INSTALL:=""}"

declare -x INVOICENINJA_UPDATE_SECRET
: "${INVOICENINJA_UPDATE_SECRET:=""}"

declare -x INVOICENINJA_BACKUP_DISK
: "${INVOICENINJA_BACKUP_DISK:=""}"

declare -x INVOICENINJA_DOCUMENT_DISK
: "${INVOICENINJA_DOCUMENT_DISK:=""}"

declare -x INVOICENINJA_TERMS_OF_SERVICE_URL
: "${INVOICENINJA_TERMS_OF_SERVICE_URL:=""}"

declare -x INVOICENINJA_PRIVACY_POLICY_URL
: "${INVOICENINJA_PRIVACY_POLICY_URL:=""}"
