#!/usr/bin/env bash

declare -x INVOICENINJA_QUEUE_CONNECTION
[[ -z "${INVOICENINJA_QUEUE_CONNECTION}" ]] && INVOICENINJA_QUEUE_CONNECTION="sync"

declare -x INVOICENINJA_SQS_PREFIX
[[ -z "${INVOICENINJA_SQS_PREFIX}" ]] && INVOICENINJA_SQS_PREFIX=""

declare -x INVOICENINJA_SQS_QUEUE
[[ -z "${INVOICENINJA_SQS_QUEUE}" ]] && INVOICENINJA_SQS_QUEUE=""

declare -x INVOICENINJA_SQS_SUFFIX
[[ -z "${INVOICENINJA_SQS_SUFFIX}" ]] && INVOICENINJA_SQS_SUFFIX=""

declare -x INVOICENINJA_REDIS_QUEUE_CONNECTION
[[ -z "${INVOICENINJA_REDIS_QUEUE_CONNECTION}" ]] && INVOICENINJA_REDIS_QUEUE_CONNECTION="default"

declare -x INVOICENINJA_REDIS_QUEUE
[[ -z "${INVOICENINJA_REDIS_QUEUE}" ]] && INVOICENINJA_REDIS_QUEUE="default"

declare -x INVOICENINJA_QUEUE_FAILED_DRIVER
[[ -z "${INVOICENINJA_QUEUE_FAILED_DRIVER}" ]] && INVOICENINJA_QUEUE_FAILED_DRIVER="database-uuids"

true
