#!/usr/bin/env bash

declare -x INVOICENINJA_TRACKING_ID
[[ -z "${INVOICENINJA_TRACKING_ID}" ]] && INVOICENINJA_TRACKING_ID=""

declare -x INVOICENINJA_MAILGUN_DOMAIN
[[ -z "${INVOICENINJA_MAILGUN_DOMAIN}" ]] && INVOICENINJA_MAILGUN_DOMAIN=""

declare -x INVOICENINJA_MAILGUN_SECRET
[[ -z "${INVOICENINJA_MAILGUN_SECRET}" ]] && INVOICENINJA_MAILGUN_SECRET=""

declare -x INVOICENINJA_MAILGUN_ENDPOINT
[[ -z "${INVOICENINJA_MAILGUN_ENDPOINT}" ]] && INVOICENINJA_MAILGUN_ENDPOINT=""

declare -x INVOICENINJA_MAILGUN_WEBHOOK_SIGNING_KEY
[[ -z "${INVOICENINJA_MAILGUN_WEBHOOK_SIGNING_KEY}" ]] && INVOICENINJA_MAILGUN_WEBHOOK_SIGNING_KEY=""

declare -x INVOICENINJA_MAILGUN_FROM_ADDRESS
[[ -z "${INVOICENINJA_MAILGUN_FROM_ADDRESS}" ]] && INVOICENINJA_MAILGUN_FROM_ADDRESS=""

declare -x INVOICENINJA_MAILGUN_FROM_NAME
[[ -z "${INVOICENINJA_MAILGUN_FROM_NAME}" ]] && INVOICENINJA_MAILGUN_FROM_NAME=""

declare -x INVOICENINJA_BREVO_SECRET
[[ -z "${INVOICENINJA_BREVO_SECRET}" ]] && INVOICENINJA_BREVO_SECRET=""

declare -x INVOICENINJA_POSTMARK_SECRET
[[ -z "${INVOICENINJA_POSTMARK_SECRET}" ]] && INVOICENINJA_POSTMARK_SECRET=""

declare -x INVOICENINJA_POSTMARK_OUTLOOK_SECRET
[[ -z "${INVOICENINJA_POSTMARK_OUTLOOK_SECRET}" ]] && INVOICENINJA_POSTMARK_OUTLOOK_SECRET=""

declare -x INVOICENINJA_POSTMARK_OUTLOOK_FROM_ADDRESS
[[ -z "${INVOICENINJA_POSTMARK_OUTLOOK_FROM_ADDRESS}" ]] && INVOICENINJA_POSTMARK_OUTLOOK_FROM_ADDRESS=""

declare -x INVOICENINJA_MICROSOFT_CLIENT_ID
[[ -z "${INVOICENINJA_MICROSOFT_CLIENT_ID}" ]] && INVOICENINJA_MICROSOFT_CLIENT_ID=""

declare -x INVOICENINJA_MICROSOFT_CLIENT_SECRET
[[ -z "${INVOICENINJA_MICROSOFT_CLIENT_SECRET}" ]] && INVOICENINJA_MICROSOFT_CLIENT_SECRET=""

declare -x INVOICENINJA_MICROSOFT_REDIRECT_URI
[[ -z "${INVOICENINJA_MICROSOFT_REDIRECT_URI}" ]] && INVOICENINJA_MICROSOFT_REDIRECT_URI="${INVOICENINJA_APP_URL}/auth/microsoft"

declare -x INVOICENINJA_APPLE_CLIENT_ID
[[ -z "${INVOICENINJA_APPLE_CLIENT_ID}" ]] && INVOICENINJA_APPLE_CLIENT_ID=""

declare -x INVOICENINJA_APPLE_CLIENT_SECRET
[[ -z "${INVOICENINJA_APPLE_CLIENT_SECRET}" ]] && INVOICENINJA_APPLE_CLIENT_SECRET=""

declare -x INVOICENINJA_APPLE_REDIRECT_URI
[[ -z "${INVOICENINJA_APPLE_REDIRECT_URI}" ]] && INVOICENINJA_APPLE_REDIRECT_URI="${INVOICENINJA_APP_URL}/auth/apple"

declare -x INVOICENINJA_SES_REGION
[[ -z "${INVOICENINJA_SES_REGION}" ]] && INVOICENINJA_SES_REGION=""

declare -x INVOICENINJA_SPARKPOST_SECRET
[[ -z "${INVOICENINJA_SPARKPOST_SECRET}" ]] && INVOICENINJA_SPARKPOST_SECRET=""

declare -x INVOICENINJA_STRIPE_KEY
[[ -z "${INVOICENINJA_STRIPE_KEY}" ]] && INVOICENINJA_STRIPE_KEY=""

declare -x INVOICENINJA_STRIPE_SECRET
[[ -z "${INVOICENINJA_STRIPE_SECRET}" ]] && INVOICENINJA_STRIPE_SECRET=""

declare -x INVOICENINJA_GITHUB_CLIENT_ID
[[ -z "${INVOICENINJA_GITHUB_CLIENT_ID}" ]] && INVOICENINJA_GITHUB_CLIENT_ID=""

declare -x INVOICENINJA_GITHUB_CLIENT_SECRET
[[ -z "${INVOICENINJA_GITHUB_CLIENT_SECRET}" ]] && INVOICENINJA_GITHUB_CLIENT_SECRET=""

declare -x INVOICENINJA_GITHUB_OAUTH_REDIRECT
[[ -z "${INVOICENINJA_GITHUB_OAUTH_REDIRECT}" ]] && INVOICENINJA_GITHUB_OAUTH_REDIRECT="${INVOICENINJA_APP_URL}/auth/github"

declare -x INVOICENINJA_GOOGLE_CLIENT_ID
[[ -z "${INVOICENINJA_GOOGLE_CLIENT_ID}" ]] && INVOICENINJA_GOOGLE_CLIENT_ID=""

declare -x INVOICENINJA_GOOGLE_CLIENT_SECRET
[[ -z "${INVOICENINJA_GOOGLE_CLIENT_SECRET}" ]] && INVOICENINJA_GOOGLE_CLIENT_SECRET=""

declare -x INVOICENINJA_GOOGLE_OAUTH_REDIRECT
[[ -z "${INVOICENINJA_GOOGLE_OAUTH_REDIRECT}" ]] && INVOICENINJA_GOOGLE_OAUTH_REDIRECT="${INVOICENINJA_APP_URL}/auth/google"

declare -x INVOICENINJA_FACEBOOK_CLIENT_ID
[[ -z "${INVOICENINJA_FACEBOOK_CLIENT_ID}" ]] && INVOICENINJA_FACEBOOK_CLIENT_ID=""

declare -x INVOICENINJA_FACEBOOK_CLIENT_SECRET
[[ -z "${INVOICENINJA_FACEBOOK_CLIENT_SECRET}" ]] && INVOICENINJA_FACEBOOK_CLIENT_SECRET=""

declare -x INVOICENINJA_FACEBOOK_OAUTH_REDIRECT
[[ -z "${INVOICENINJA_FACEBOOK_OAUTH_REDIRECT}" ]] && INVOICENINJA_FACEBOOK_OAUTH_REDIRECT="${INVOICENINJA_APP_URL}/auth/facebook"

declare -x INVOICENINJA_LINKEDIN_CLIENT_ID
[[ -z "${INVOICENINJA_LINKEDIN_CLIENT_ID}" ]] && INVOICENINJA_LINKEDIN_CLIENT_ID=""

declare -x INVOICENINJA_LINKEDIN_CLIENT_SECRET
[[ -z "${INVOICENINJA_LINKEDIN_CLIENT_SECRET}" ]] && INVOICENINJA_LINKEDIN_CLIENT_SECRET=""

declare -x INVOICENINJA_LINKEDIN_OAUTH_REDIRECT
[[ -z "${INVOICENINJA_LINKEDIN_OAUTH_REDIRECT}" ]] && INVOICENINJA_LINKEDIN_OAUTH_REDIRECT="${INVOICENINJA_APP_URL}/auth/linkedin"

declare -x INVOICENINJA_TWITTER_CLIENT_ID
[[ -z "${INVOICENINJA_TWITTER_CLIENT_ID}" ]] && INVOICENINJA_TWITTER_CLIENT_ID=""

declare -x INVOICENINJA_TWITTER_CLIENT_SECRET
[[ -z "${INVOICENINJA_TWITTER_CLIENT_SECRET}" ]] && INVOICENINJA_TWITTER_CLIENT_SECRET=""

declare -x INVOICENINJA_TWITTER_OAUTH_REDIRECT
[[ -z "${INVOICENINJA_TWITTER_OAUTH_REDIRECT}" ]] && INVOICENINJA_TWITTER_OAUTH_REDIRECT="${INVOICENINJA_APP_URL}/auth/twitter"

declare -x INVOICENINJA_BITBUCKET_CLIENT_ID
[[ -z "${INVOICENINJA_BITBUCKET_CLIENT_ID}" ]] && INVOICENINJA_BITBUCKET_CLIENT_ID=""

declare -x INVOICENINJA_BITBUCKET_CLIENT_SECRET
[[ -z "${INVOICENINJA_BITBUCKET_CLIENT_SECRET}" ]] && INVOICENINJA_BITBUCKET_CLIENT_SECRET=""

declare -x INVOICENINJA_BITBUCKET_OAUTH_REDIRECT
[[ -z "${INVOICENINJA_BITBUCKET_OAUTH_REDIRECT}" ]] && INVOICENINJA_BITBUCKET_OAUTH_REDIRECT="${INVOICENINJA_APP_URL}/auth/bitbucket"

declare -x INVOICENINJA_ZIP_TAX_KEY
[[ -z "${INVOICENINJA_ZIP_TAX_KEY}" ]] && INVOICENINJA_ZIP_TAX_KEY=""

declare -x INVOICENINJA_CHORUS_CLIENT_ID
[[ -z "${INVOICENINJA_CHORUS_CLIENT_ID}" ]] && INVOICENINJA_CHORUS_CLIENT_ID=""

declare -x INVOICENINJA_CHORUS_SECRET
[[ -z "${INVOICENINJA_CHORUS_SECRET}" ]] && INVOICENINJA_CHORUS_SECRET=""

true
