#!/usr/bin/env bash

declare -x INVOICENINJA_SESSION_DRIVER
: "${INVOICENINJA_SESSION_DRIVER:="file"}"

declare -x INVOICENINJA_SESSION_LIFETIME
: "${INVOICENINJA_SESSION_LIFETIME:="120"}"

declare -x INVOICENINJA_SESSION_CONNECTION
: "${INVOICENINJA_SESSION_CONNECTION:=""}"

declare -x INVOICENINJA_SESSION_STORE
: "${INVOICENINJA_SESSION_STORE:=""}"

declare -x INVOICENINJA_SESSION_COOKIE
: "${INVOICENINJA_SESSION_COOKIE:=""}"

declare -x INVOICENINJA_SESSION_DOMAIN
: "${INVOICENINJA_SESSION_DOMAIN:=""}"

declare -x INVOICENINJA_SESSION_SECURE_COOKIE
: "${INVOICENINJA_SESSION_SECURE_COOKIE:=""}"

declare -x INVOICENINJA_SESSION_SAME_SITE
: "${INVOICENINJA_SESSION_SAME_SITE:=""}"
