FROM ghcr.io/dockhippie/php-apache:8.4-amd64@sha256:7fa8595f7a83858d29f127291a1c0416309b3188d77b0afb7a1eb2b92b75c6fc

VOLUME ["/var/lib/invoiceninja"]
EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  apk add php${PHP_PACKAGE_VERSION}-pecl-apcu sqlite git && \
  rm -rf /var/cache/apk/*

ENV PHP_COMPOSER_INSTALL=false

# renovate: datasource=github-releases depName=invoiceninja/invoiceninja
ENV INVOICENINJA_VERSION=5.10.62

# renovate: datasource=github-releases depName=aptible/supercronic
ENV SUPERCRONIC_VERSION=0.2.43

RUN curl -sSLo - https://github.com/invoiceninja/invoiceninja/releases/download/v${INVOICENINJA_VERSION}/invoiceninja.tar | tar -xzf - -C /srv/www && \
  cd /srv/www && \
  rm -f /srv/www/.env* && \
  chown -R apache:apache /srv/www && \
  curl -sSLo /usr/bin/supercronic https://github.com/aptible/supercronic/releases/download/v${SUPERCRONIC_VERSION}/supercronic-linux-amd64 && \
  chmod +x /usr/bin/supercronic

COPY ./overlay /

RUN find /etc/container.d /etc/entrypoint.d -type f -name \*.sh -exec sed -i 's/\r$//' {} +; \
  sed -i 's/\r$//' /usr/bin/container* && \
  chmod +x /usr/bin/container* /etc/container.d/*.sh /etc/entrypoint.d/*.sh
