#!/bin/bash

if [ "$(ls -A /app/storage/templates)" == "" ]
then
  wget \
    -qO /app/storage/templates/plain.js \
    https://raw.githubusercontent.com/invoiceninja/invoiceninja/v2.4.9.1/storage/templates/plain.js
fi
