#!/bin/bash

declare -x INVOICENINJA_DB_TYPE
[[ -z "${INVOICENINJA_DB_TYPE}" ]] && INVOICENINJA_DB_TYPE="sqlite"

case "${INVOICENINJA_DB_TYPE}" in
  "sqlite")
    declare -x INVOICENINJA_DB_DATABASE
    [[ -z "${INVOICENINJA_DB_DATABASE}" ]] && INVOICENINJA_DB_DATABASE="${INVOICENINJA_BASE_DIR}/database.sqlite3"

    declare -x INVOICENINJA_DB_PREFIX
    [[ -z "${INVOICENINJA_DB_PREFIX}" ]] && INVOICENINJA_DB_PREFIX=""
    ;;

  "mysql")
    declare -x INVOICENINJA_DB_HOST
    [[ -z "${INVOICENINJA_DB_HOST}" ]] && INVOICENINJA_DB_HOST="mysql"

    declare -x INVOICENINJA_DB_PORT
    [[ -z "${INVOICENINJA_DB_PORT}" ]] && INVOICENINJA_DB_PORT="3306"

    declare -x INVOICENINJA_DB_DATABASE
    [[ -z "${INVOICENINJA_DB_DATABASE}" ]] && INVOICENINJA_DB_DATABASE="ninja"

    declare -x INVOICENINJA_DB_USERNAME
    [[ -z "${INVOICENINJA_DB_USERNAME}" ]] && INVOICENINJA_DB_USERNAME="root"

    declare -x INVOICENINJA_DB_PASSWORD
    [[ -z "${INVOICENINJA_DB_PASSWORD}" ]] && INVOICENINJA_DB_PASSWORD="root"

    declare -x INVOICENINJA_DB_PREFIX
    [[ -z "${INVOICENINJA_DB_PREFIX}" ]] && INVOICENINJA_DB_PREFIX=""

    declare -x INVOICENINJA_DB_CHARSET
    [[ -z "${INVOICENINJA_DB_CHARSET}" ]] && INVOICENINJA_DB_CHARSET="utf8"

    declare -x INVOICENINJA_DB_COLLATION
    [[ -z "${INVOICENINJA_DB_COLLATION}" ]] && INVOICENINJA_DB_COLLATION="utf8_general_ci"

    declare -x INVOICENINJA_DB_STRICT
    [[ -z "${INVOICENINJA_DB_STRICT}" ]] && INVOICENINJA_DB_STRICT="false"
    ;;

  "pgsql")
    declare -x INVOICENINJA_DB_HOST
    [[ -z "${INVOICENINJA_DB_HOST}" ]] && INVOICENINJA_DB_HOST="postgres"

    declare -x INVOICENINJA_DB_PORT
    [[ -z "${INVOICENINJA_DB_PORT}" ]] && INVOICENINJA_DB_PORT="5432"

    declare -x INVOICENINJA_DB_DATABASE
    [[ -z "${INVOICENINJA_DB_DATABASE}" ]] && INVOICENINJA_DB_DATABASE="ninja"

    declare -x INVOICENINJA_DB_USERNAME
    [[ -z "${INVOICENINJA_DB_USERNAME}" ]] && INVOICENINJA_DB_USERNAME="root"

    declare -x INVOICENINJA_DB_PASSWORD
    [[ -z "${INVOICENINJA_DB_PASSWORD}" ]] && INVOICENINJA_DB_PASSWORD="root"

    declare -x INVOICENINJA_DB_PREFIX
    [[ -z "${INVOICENINJA_DB_PREFIX}" ]] && INVOICENINJA_DB_PREFIX="utf8"

    declare -x INVOICENINJA_DB_CHARSET
    [[ -z "${INVOICENINJA_DB_CHARSET}" ]] && INVOICENINJA_DB_CHARSET="utf8"

    declare -x INVOICENINJA_DB_SCHEMA
    [[ -z "${INVOICENINJA_DB_SCHEMA}" ]] && INVOICENINJA_DB_SCHEMA="public"
    ;;
esac

declare -x INVOICENINJA_REDIS_HOST
[[ -z "${INVOICENINJA_REDIS_HOST}" ]] && INVOICENINJA_REDIS_HOST="redis"

declare -x INVOICENINJA_REDIS_PORT
[[ -z "${INVOICENINJA_REDIS_PORT}" ]] && INVOICENINJA_REDIS_PORT="6379"

declare -x INVOICENINJA_REDIS_DATABASE
[[ -z "${INVOICENINJA_REDIS_DATABASE}" ]] && INVOICENINJA_REDIS_DATABASE="0"
