#!/bin/bash

declare -x INVOICENINJA_FILESYSTEMS_DEFAULT
[[ -z "${INVOICENINJA_FILESYSTEMS_DEFAULT}" ]] && INVOICENINJA_FILESYSTEMS_DEFAULT="local"

declare -x INVOICENINJA_FILESYSTEMS_CLOUD
[[ -z "${INVOICENINJA_FILESYSTEMS_CLOUD}" ]] && INVOICENINJA_FILESYSTEMS_CLOUD="s3"

declare -x INVOICENINJA_LOGO_PATH
[[ -z "${INVOICENINJA_LOGO_PATH}" ]] && INVOICENINJA_LOGO_PATH=""

declare -x INVOICENINJA_FILESYSTEMS_S3_KEY
[[ -z "${INVOICENINJA_FILESYSTEMS_S3_KEY}" ]] && INVOICENINJA_FILESYSTEMS_S3_KEY=""

declare -x INVOICENINJA_FILESYSTEMS_S3_SECRET
[[ -z "${INVOICENINJA_FILESYSTEMS_S3_SECRET}" ]] && INVOICENINJA_FILESYSTEMS_S3_SECRET=""

declare -x INVOICENINJA_FILESYSTEMS_S3_REGION
[[ -z "${INVOICENINJA_FILESYSTEMS_S3_REGION}" ]] && INVOICENINJA_FILESYSTEMS_S3_REGION="us-east-1"

declare -x INVOICENINJA_FILESYSTEMS_S3_BUCKET
[[ -z "${INVOICENINJA_FILESYSTEMS_S3_BUCKET}" ]] && INVOICENINJA_FILESYSTEMS_S3_BUCKET=""

declare -x INVOICENINJA_FILESYSTEMS_RACKSPACE_USERNAME
[[ -z "${INVOICENINJA_FILESYSTEMS_RACKSPACE_USERNAME}" ]] && INVOICENINJA_FILESYSTEMS_RACKSPACE_USERNAME=""

declare -x INVOICENINJA_FILESYSTEMS_RACKSPACE_KEY
[[ -z "${INVOICENINJA_FILESYSTEMS_RACKSPACE_KEY}" ]] && INVOICENINJA_FILESYSTEMS_RACKSPACE_KEY=""

declare -x INVOICENINJA_FILESYSTEMS_RACKSPACE_CONTAINER
[[ -z "${INVOICENINJA_FILESYSTEMS_RACKSPACE_CONTAINER}" ]] && INVOICENINJA_FILESYSTEMS_RACKSPACE_CONTAINER=""

declare -x INVOICENINJA_FILESYSTEMS_RACKSPACE_ENDPOINT
[[ -z "${INVOICENINJA_FILESYSTEMS_RACKSPACE_ENDPOINT}" ]] && INVOICENINJA_FILESYSTEMS_RACKSPACE_ENDPOINT="https://identity.api.rackspacecloud.com/v2.0/"

declare -x INVOICENINJA_FILESYSTEMS_RACKSPACE_REGION
[[ -z "${INVOICENINJA_FILESYSTEMS_RACKSPACE_REGION}" ]] && INVOICENINJA_FILESYSTEMS_RACKSPACE_REGION="IAD"

declare -x INVOICENINJA_FILESYSTEMS_RACKSPACE_URL_TYPE
[[ -z "${INVOICENINJA_FILESYSTEMS_RACKSPACE_URL_TYPE}" ]] && INVOICENINJA_FILESYSTEMS_RACKSPACE_URL_TYPE="publicURL"

declare -x INVOICENINJA_FILESYSTEMS_GCS_BUCKET
[[ -z "${INVOICENINJA_FILESYSTEMS_GCS_BUCKET}" ]] && INVOICENINJA_FILESYSTEMS_GCS_BUCKET="cloud-storage-bucket"

declare -x INVOICENINJA_FILESYSTEMS_GCS_PROJECT_ID
[[ -z "${INVOICENINJA_FILESYSTEMS_GCS_PROJECT_ID}" ]] && INVOICENINJA_FILESYSTEMS_GCS_PROJECT_ID=""

declare -x INVOICENINJA_FILESYSTEMS_GCS_CREDENTIALS_PATH
[[ -z "${INVOICENINJA_FILESYSTEMS_GCS_CREDENTIALS_PATH}" ]] && INVOICENINJA_FILESYSTEMS_GCS_CREDENTIALS_PATH=""
