#!/bin/bash

declare -x INVOICENINJA_PHANTOMJS_SECRET
[[ -z "${INVOICENINJA_PHANTOMJS_SECRET}" ]] && INVOICENINJA_PHANTOMJS_SECRET=""

declare -x INVOICENINJA_PHANTOMJS_BIN_PATH
[[ -z "${INVOICENINJA_PHANTOMJS_BIN_PATH}" ]] && INVOICENINJA_PHANTOMJS_BIN_PATH=""

declare -x INVOICENINJA_PHANTOMJS_CLOUD_KEY
[[ -z "${INVOICENINJA_PHANTOMJS_CLOUD_KEY}" ]] && INVOICENINJA_PHANTOMJS_CLOUD_KEY=""
