#!/bin/bash

declare -x INVOICENINJA_PUSH_IOS_CERTIFICATE_PATH
[[ -z "${INVOICENINJA_PUSH_IOS_CERTIFICATE_PATH}" ]] && INVOICENINJA_PUSH_IOS_CERTIFICATE_PATH=""

declare -x INVOICENINJA_PUSH_IOS_PASSPHRASE
[[ -z "${INVOICENINJA_PUSH_IOS_PASSPHRASE}" ]] && INVOICENINJA_PUSH_IOS_PASSPHRASE=""

declare -x INVOICENINJA_PUSH_ANDROID_APIKEY
[[ -z "${INVOICENINJA_PUSH_ANDROID_APIKEY}" ]] && INVOICENINJA_PUSH_ANDROID_APIKEY=""
