#!/bin/bash

declare -x INVOICENINJA_POSTMARK_API_TOKEN
[[ -z "${INVOICENINJA_POSTMARK_API_TOKEN}" ]] && INVOICENINJA_POSTMARK_API_TOKEN=""

declare -x INVOICENINJA_MAILGUN_DOMAIN
[[ -z "${INVOICENINJA_MAILGUN_DOMAIN}" ]] && INVOICENINJA_MAILGUN_DOMAIN=""

declare -x INVOICENINJA_MAILGUN_SECRET
[[ -z "${INVOICENINJA_MAILGUN_SECRET}" ]] && INVOICENINJA_MAILGUN_SECRET=""

declare -x INVOICENINJA_MANDRILL_SECRET
[[ -z "${INVOICENINJA_MANDRILL_SECRET}" ]] && INVOICENINJA_MANDRILL_SECRET=""

declare -x INVOICENINJA_SPARKPOST_SECRET
[[ -z "${INVOICENINJA_SPARKPOST_SECRET}" ]] && INVOICENINJA_SPARKPOST_SECRET=""

declare -x INVOICENINJA_SES_KEY
[[ -z "${INVOICENINJA_SES_KEY}" ]] && INVOICENINJA_SES_KEY=""

declare -x INVOICENINJA_SES_SECRET
[[ -z "${INVOICENINJA_SES_SECRET}" ]] && INVOICENINJA_SES_SECRET=""

declare -x INVOICENINJA_SES_REGION
[[ -z "${INVOICENINJA_SES_REGION}" ]] && INVOICENINJA_SES_REGION="us-east-1"

declare -x INVOICENINJA_STRIPE_MODEL
[[ -z "${INVOICENINJA_STRIPE_MODEL}" ]] && INVOICENINJA_STRIPE_MODEL="User"

declare -x INVOICENINJA_STRIPE_SECRET
[[ -z "${INVOICENINJA_STRIPE_SECRET}" ]] && INVOICENINJA_STRIPE_SECRET=""

declare -x INVOICENINJA_GITHUB_CLIENT_ID
[[ -z "${INVOICENINJA_GITHUB_CLIENT_ID}" ]] && INVOICENINJA_GITHUB_CLIENT_ID=""

declare -x INVOICENINJA_GITHUB_CLIENT_SECRET
[[ -z "${INVOICENINJA_GITHUB_CLIENT_SECRET}" ]] && INVOICENINJA_GITHUB_CLIENT_SECRET=""

declare -x INVOICENINJA_GITHUB_OAUTH_REDIRECT
[[ -z "${INVOICENINJA_GITHUB_OAUTH_REDIRECT}" ]] && INVOICENINJA_GITHUB_OAUTH_REDIRECT=""

declare -x INVOICENINJA_GOOGLE_CLIENT_ID
[[ -z "${INVOICENINJA_GOOGLE_CLIENT_ID}" ]] && INVOICENINJA_GOOGLE_CLIENT_ID=""

declare -x INVOICENINJA_GOOGLE_CLIENT_SECRET
[[ -z "${INVOICENINJA_GOOGLE_CLIENT_SECRET}" ]] && INVOICENINJA_GOOGLE_CLIENT_SECRET=""

declare -x INVOICENINJA_GOOGLE_OAUTH_REDIRECT
[[ -z "${INVOICENINJA_GOOGLE_OAUTH_REDIRECT}" ]] && INVOICENINJA_GOOGLE_OAUTH_REDIRECT=""

declare -x INVOICENINJA_FACEBOOK_CLIENT_ID
[[ -z "${INVOICENINJA_FACEBOOK_CLIENT_ID}" ]] && INVOICENINJA_FACEBOOK_CLIENT_ID=""

declare -x INVOICENINJA_FACEBOOK_CLIENT_SECRET
[[ -z "${INVOICENINJA_FACEBOOK_CLIENT_SECRET}" ]] && INVOICENINJA_FACEBOOK_CLIENT_SECRET=""

declare -x INVOICENINJA_FACEBOOK_OAUTH_REDIRECT
[[ -z "${INVOICENINJA_FACEBOOK_OAUTH_REDIRECT}" ]] && INVOICENINJA_FACEBOOK_OAUTH_REDIRECT=""

declare -x INVOICENINJA_LINKEDIN_CLIENT_ID
[[ -z "${INVOICENINJA_LINKEDIN_CLIENT_ID}" ]] && INVOICENINJA_LINKEDIN_CLIENT_ID=""

declare -x INVOICENINJA_LINKEDIN_CLIENT_SECRET
[[ -z "${INVOICENINJA_LINKEDIN_CLIENT_SECRET}" ]] && INVOICENINJA_LINKEDIN_CLIENT_SECRET=""

declare -x INVOICENINJA_LINKEDIN_OAUTH_REDIRECT
[[ -z "${INVOICENINJA_LINKEDIN_OAUTH_REDIRECT}" ]] && INVOICENINJA_LINKEDIN_OAUTH_REDIRECT=""
