#!/bin/bash

declare -x INVOICENINJA_BASE_DIR
[[ -z "${INVOICENINJA_BASE_DIR}" ]] && INVOICENINJA_BASE_DIR="/var/lib/invoiceninja"

declare -x INVOICENINJA_APP_ENV
[[ -z "${INVOICENINJA_APP_ENV}" ]] && INVOICENINJA_APP_ENV="production"

declare -x INVOICENINJA_APP_DEBUG
[[ -z "${INVOICENINJA_APP_DEBUG}" ]] && INVOICENINJA_APP_DEBUG="false"

declare -x INVOICENINJA_APP_URL
[[ -z "${INVOICENINJA_APP_URL}" ]] && INVOICENINJA_APP_URL="http://localhost"

declare -x INVOICENINJA_APP_CIPHER
[[ -z "${INVOICENINJA_APP_CIPHER}" ]] && INVOICENINJA_APP_CIPHER="rijndael-128"

declare -x INVOICENINJA_APP_KEY
[[ -z "${INVOICENINJA_APP_KEY}" ]] && INVOICENINJA_APP_KEY="UTC"

declare -x INVOICENINJA_APP_TIMEZONE
[[ -z "${INVOICENINJA_APP_TIMEZONE}" ]] && INVOICENINJA_APP_TIMEZONE="UTC"

declare -x INVOICENINJA_APP_LOCALE
[[ -z "${INVOICENINJA_APP_LOCALE}" ]] && INVOICENINJA_APP_LOCALE="en"

declare -x INVOICENINJA_DB_TYPE
[[ -z "${INVOICENINJA_DB_TYPE}" ]] && INVOICENINJA_DB_TYPE="mysql"

declare -x INVOICENINJA_DB_STRICT
[[ -z "${INVOICENINJA_DB_STRICT}" ]] && INVOICENINJA_DB_STRICT=""

declare -x INVOICENINJA_DB_HOST
[[ -z "${INVOICENINJA_DB_HOST}" ]] && INVOICENINJA_DB_HOST=""

declare -x INVOICENINJA_DB_DATABASE
[[ -z "${INVOICENINJA_DB_DATABASE}" ]] && INVOICENINJA_DB_DATABASE=""

declare -x INVOICENINJA_DB_USERNAME
[[ -z "${INVOICENINJA_DB_USERNAME}" ]] && INVOICENINJA_DB_USERNAME=""

declare -x INVOICENINJA_DB_PASSWORD
[[ -z "${INVOICENINJA_DB_PASSWORD}" ]] && INVOICENINJA_DB_PASSWORD=""

declare -x INVOICENINJA_MAIL_DRIVER
[[ -z "${INVOICENINJA_MAIL_DRIVER}" ]] && INVOICENINJA_MAIL_DRIVER="smtp"

declare -x INVOICENINJA_MAIL_PORT
[[ -z "${INVOICENINJA_MAIL_PORT}" ]] && INVOICENINJA_MAIL_PORT="587"

declare -x INVOICENINJA_MAIL_ENCRYPTION
[[ -z "${INVOICENINJA_MAIL_ENCRYPTION}" ]] && INVOICENINJA_MAIL_ENCRYPTION="tls"

declare -x INVOICENINJA_MAIL_HOST
[[ -z "${INVOICENINJA_MAIL_HOST}" ]] && INVOICENINJA_MAIL_HOST="localhosr"

declare -x INVOICENINJA_MAIL_USERNAME
[[ -z "${INVOICENINJA_MAIL_USERNAME}" ]] && INVOICENINJA_MAIL_USERNAME=""

declare -x INVOICENINJA_MAIL_ADDRESS
[[ -z "${INVOICENINJA_MAIL_ADDRESS}" ]] && INVOICENINJA_MAIL_ADDRESS="invoiceninja@localhost"

declare -x INVOICENINJA_MAIL_NAME
[[ -z "${INVOICENINJA_MAIL_NAME}" ]] && INVOICENINJA_MAIL_NAME="Invoiceninja"

declare -x INVOICENINJA_MAIL_PASSWORD
[[ -z "${INVOICENINJA_MAIL_PASSWORD}" ]] && INVOICENINJA_MAIL_PASSWORD=""

declare -x INVOICENINJA_PHANTOMJS_CLOUD_KEY
[[ -z "${INVOICENINJA_PHANTOMJS_CLOUD_KEY}" ]] && INVOICENINJA_PHANTOMJS_CLOUD_KEY=""

declare -x INVOICENINJA_LOG
[[ -z "${INVOICENINJA_LOG}" ]] && INVOICENINJA_LOG="single"

declare -x INVOICENINJA_REQUIRE_HTTPS
[[ -z "${INVOICENINJA_REQUIRE_HTTPS}" ]] && INVOICENINJA_REQUIRE_HTTPS="false"

declare -x INVOICENINJA_GITHUB_CLIENT_ID
[[ -z "${INVOICENINJA_GITHUB_CLIENT_ID}" ]] && INVOICENINJA_GITHUB_CLIENT_ID=""

declare -x INVOICENINJA_GITHUB_CLIENT_SECRET
[[ -z "${INVOICENINJA_GITHUB_CLIENT_SECRET}" ]] && INVOICENINJA_GITHUB_CLIENT_SECRET=""

declare -x INVOICENINJA_GOOGLE_CLIENT_ID
[[ -z "${INVOICENINJA_GOOGLE_CLIENT_ID}" ]] && INVOICENINJA_GOOGLE_CLIENT_ID=""

declare -x INVOICENINJA_GOOGLE_CLIENT_SECRET
[[ -z "${INVOICENINJA_GOOGLE_CLIENT_SECRET}" ]] && INVOICENINJA_GOOGLE_CLIENT_SECRET=""

declare -x INVOICENINJA_FACEBOOK_CLIENT_ID
[[ -z "${INVOICENINJA_FACEBOOK_CLIENT_ID}" ]] && INVOICENINJA_FACEBOOK_CLIENT_ID=""

declare -x INVOICENINJA_FACEBOOK_CLIENT_SECRET
[[ -z "${INVOICENINJA_FACEBOOK_CLIENT_SECRET}" ]] && INVOICENINJA_FACEBOOK_CLIENT_SECRET=""

declare -x INVOICENINJA_LINKEDIN_CLIENT_ID
[[ -z "${INVOICENINJA_LINKEDIN_CLIENT_ID}" ]] && INVOICENINJA_LINKEDIN_CLIENT_ID=""

declare -x INVOICENINJA_LINKEDIN_CLIENT_SECRET
[[ -z "${INVOICENINJA_LINKEDIN_CLIENT_SECRET}" ]] && INVOICENINJA_LINKEDIN_CLIENT_SECRET=""

case "${INVOICENINJA_DB_TYPE}" in
  "sqlite")
    declare -x INVOICENINJA_DB_DATABASE
    [[ -z "${INVOICENINJA_DB_DATABASE}" ]] && INVOICENINJA_DB_DATABASE="${INVOICENINJA_BASE_DIR}/database.sqlite3"

    declare -x INVOICENINJA_DB_PREFIX
    [[ -z "${INVOICENINJA_DB_PREFIX}" ]] && INVOICENINJA_DB_PREFIX=""
    ;;

  "mysql")
    declare -x INVOICENINJA_DB_HOST
    [[ -z "${INVOICENINJA_DB_HOST}" ]] && INVOICENINJA_DB_HOST="mysql"

    declare -x INVOICENINJA_DB_DATABASE
    [[ -z "${INVOICENINJA_DB_DATABASE}" ]] && INVOICENINJA_DB_DATABASE="ninja"

    declare -x INVOICENINJA_DB_USERNAME
    [[ -z "${INVOICENINJA_DB_USERNAME}" ]] && INVOICENINJA_DB_USERNAME="root"

    declare -x INVOICENINJA_DB_PASSWORD
    [[ -z "${INVOICENINJA_DB_PASSWORD}" ]] && INVOICENINJA_DB_PASSWORD="root"

    declare -x INVOICENINJA_DB_PREFIX
    [[ -z "${INVOICENINJA_DB_PREFIX}" ]] && INVOICENINJA_DB_PREFIX=""

    declare -x INVOICENINJA_DB_CHARSET
    [[ -z "${INVOICENINJA_DB_CHARSET}" ]] && INVOICENINJA_DB_CHARSET="utf8"

    declare -x INVOICENINJA_DB_COLLATION
    [[ -z "${INVOICENINJA_DB_COLLATION}" ]] && INVOICENINJA_DB_COLLATION="utf8_general_ci"

    declare -x INVOICENINJA_DB_STRICT
    [[ -z "${INVOICENINJA_DB_STRICT}" ]] && INVOICENINJA_DB_STRICT="false"
    ;;

  "pgsql")
    declare -x INVOICENINJA_DB_HOST
    [[ -z "${INVOICENINJA_DB_HOST}" ]] && INVOICENINJA_DB_HOST="postgres"

    declare -x INVOICENINJA_DB_DATABASE
    [[ -z "${INVOICENINJA_DB_DATABASE}" ]] && INVOICENINJA_DB_DATABASE="ninja"

    declare -x INVOICENINJA_DB_USERNAME
    [[ -z "${INVOICENINJA_DB_USERNAME}" ]] && INVOICENINJA_DB_USERNAME="root"

    declare -x INVOICENINJA_DB_PASSWORD
    [[ -z "${INVOICENINJA_DB_PASSWORD}" ]] && INVOICENINJA_DB_PASSWORD="root"

    declare -x INVOICENINJA_DB_PREFIX
    [[ -z "${INVOICENINJA_DB_PREFIX}" ]] && INVOICENINJA_DB_PREFIX="utf8"

    declare -x INVOICENINJA_DB_CHARSET
    [[ -z "${INVOICENINJA_DB_CHARSET}" ]] && INVOICENINJA_DB_CHARSET="utf8"

    declare -x INVOICENINJA_DB_SCHEMA
    [[ -z "${INVOICENINJA_DB_SCHEMA}" ]] && INVOICENINJA_DB_SCHEMA="public"
    ;;
esac

if [ -z "${INVOICENINJA_APP_KEY}" ]
then
  if [ -f ${INVOICENINJA_BASE_DIR}/secret ]
  then
    INVOICENINJA_APP_KEY=$(cat ${INVOICENINJA_BASE_DIR}/secret | head -n1)
  else
    INVOICENINJA_APP_KEY=$(date +%s | sha256sum | base64 | head -c 32 ; echo)
    echo "${INVOICENINJA_APP_KEY}" > ${INVOICENINJA_BASE_DIR}/secret
  fi
fi
